[package]
name = "quoridor"
version = "0.1.0"
authors = ["Joshua Miller <jshuasmiller@gmail.com>"]

[dependencies]
iron = "*"
router = "*"
hyper = "*"

rand = "0.3"
num = "*"
log = "*"
env_logger = "*"
rustc-serialize = "0.3"
staticfile = "*"
mount = "*"
